# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches:
      - master
      - releases

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Prepare to publish
        run: |
          echo "${{ secrets.GPG_KEY_CONTENTS }}" | base64 --decode > private_key.gpg
      - name: Publish with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          arguments: build publishToSonatype closeAndReleaseSonatypeStagingRepository -Psigning.secretKeyRingFile="private_key.gpg" -Psigning.keyId="${{secrets.SIGNING_KEYID}}" -Psigning.password="${{secrets.SIGNING_PASSWORD}}" -PossSonatypeUsername="${{secrets.OSS_SONATYPE_USERNAME}}" -PossSonatypePassword="${{secrets.OSS_SONATYPE_PASSWORD}}"
